<?php
if (!defined('CSCMSPATH')) exit('No permission resources');

return array(
         'index.html' => '会员版块主页',
         'head.html' => '网站顶部',
         'bottom.html' => '网站底部',
         'gbook.html' => '留言页模板',
         'ulogin.html' => '会员登陆前',
         'uinfo.html' => '会员登录后',
         'edit.html' => '资料修改',
         'edit-pass.html' => '修改密码',
         'left.html' => '左边模板',
         'right.html' => '右边模板',
         'pass.html' => '找回密码',
         'pass-edit.html' => '找回密码修改',
         'logo.html' => '登录页面',
         'reg.html' => '注册页面',
         'space.html' => '会员中心',
         'change.html' => '金币兑换',
         'edit-logo.html' => '头像修改',
         'edit-open.html' => '账号绑定',
         'fans.html' => '粉丝列表',
         'feed-ajax.html' => '动态AJAX',
         'friend.html' => '关注列表',
         'funco.html' => '访客列表',
         'group.html' => '会员升级',
         'journal.html' => '登录日志',
         'msg-add.html' => '发送私信',
         'msg-show.html' => '阅读私信',
         'msg.html' => '私信列表',
         'open.html' => '第三方登录',
         'pay-card.html' => '充值卡充值',
         'pay-cardlist.html' => '充值卡记录',
         'pay-income.html' => '分成记录',
         'pay-list.html' => '充值记录',
         'pay-spend.html' => '消费记录',
         'pay.html' => '在线充值',
         'share-list.html' => '分享记录',
         'share.html' => '分享页面',
         'web-pic.html' => '会员主页图片',
         'web.html' => '会员主页模板',
         'blog.html' => '说说记录',
);

